from __future__ import annotations

from engines.logic_engine import get_logic_profile
from engines.copy_engine import generate_copy_profile
from engines.design_engine import get_design_system
from engines.lead_flow_engine import generate_lead_flow
from .common import common_context, readme_for, render, write_bundle


HTML = """<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8"/>
  <meta name="viewport" content="width=device-width,initial-scale=1"/>
  <title>[[ASSET_NAME]] | [[BRAND_NAME]]</title>
  <meta name="description" content="[[PROBLEM]]"/>
  <link rel="stylesheet" href="./styles.css"/>
</head>
<body>
  <main class="shell">
    <section class="hero">
      <p class="eyebrow">Calculator · [[AUDIENCE]] · T[[TIER]]</p>
      <h1>[[ASSET_NAME]]</h1>
      <p class="lede">[[PROMISE]]</p>
    </section>
    <section class="layout">
      <article class="panel">
        <h2>Inputs</h2>
        <p class="copy">[[PROBLEM]]</p>
        <form id="toolForm" class="fields"></form>
        <button id="calculate">[[CTA]]</button>
      </article>
      <article class="panel accent">
        <p class="eyebrow">Result</p>
        <div class="result" id="result">—</div>
        <p id="resultCopy">Enter your values to generate the calculator output.</p>
        <div class="stats">
          <div><span>Signal</span><b id="signal">—</b></div>
          <div><span>Action</span><b>[[CTA]]</b></div>
          <div><span>Tier</span><b>T[[TIER]]</b></div>
        </div>
      </article>
    </section>
    <section class="panel">
      <h2>Why it works</h2>
      <ul class="bullets">[[BENEFITS_HTML]]</ul>
    </section>
    <section class="panel lead" id="lead">
      <h2>Lead capture</h2>
      <div class="lead-grid">
        <input placeholder="Name"/>
        <input placeholder="Email"/>
        <input placeholder="Phone"/>
      </div>
      <button>[[CTA]]</button>
      <p class="copy">Demo form only. Connect to your CRM, webhook, or form endpoint.</p>
    </section>
    <footer class="footer">Generated by FoundryOS · [[BRAND_NAME]]</footer>
  </main>
  <script>window.FOUNDRY_SPEC=[[SPEC_JSON]];</script>
  <script src="./app.js"></script>
</body>
</html>
"""


CSS = """:root{
  color-scheme: dark;
  font-family: Inter, ui-sans-serif, system-ui;
  background:
    radial-gradient(circle at top left, rgba(214,168,79,.28), transparent 28%),
    radial-gradient(circle at 80% 0%, rgba(68,91,135,.35), transparent 30%),
    #090a0f;
  color:#f8f5ee;
}
*{box-sizing:border-box}
body{margin:0;min-height:100vh;background:transparent}
.shell{width:min(1120px,92vw);margin:auto;padding:88px 0}
.hero{margin-bottom:44px}
.eyebrow{letter-spacing:.22em;text-transform:uppercase;color:#d6a84f;font-size:12px}
h1{font-size:clamp(48px,8vw,94px);line-height:.92;margin:0 0 20px}
.lede{font-size:24px;color:#d9d2c7;max-width:760px;margin:0}
.layout{display:grid;grid-template-columns:1.08fr .92fr;gap:24px;margin-bottom:24px}
.panel{background:rgba(17,20,29,.9);border:1px solid #2b3243;border-radius:28px;padding:28px;box-shadow:0 20px 70px rgba(0,0,0,.25)}
.panel.accent{background:linear-gradient(180deg,rgba(19,25,38,.96),rgba(13,15,22,.94))}
.fields{display:grid;gap:14px;margin-top:14px}
label{display:block;margin:0 0 6px;color:#e2dacb}
input,select,textarea{width:100%;border:1px solid #394154;background:#0b0d14;color:#fff;border-radius:14px;padding:15px;font-size:16px}
button,.button{display:inline-flex;align-items:center;justify-content:center;margin-top:18px;border:0;border-radius:999px;background:#f8f5ee;color:#090a0f;padding:15px 22px;font-weight:900;text-decoration:none;cursor:pointer}
.result{font-size:44px;font-weight:950;color:#91ffbf;margin:8px 0 12px}
.copy{color:#c7beb1;line-height:1.6}
.stats{display:grid;grid-template-columns:repeat(3,1fr);gap:14px;margin-top:22px}
.stats div{border:1px solid #30384b;border-radius:18px;padding:18px}
.stats span{display:block;color:#c7beb1;font-size:13px}
.stats b{font-size:22px}
.bullets{line-height:1.9;margin:0;padding-left:18px}
.lead-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:12px}
.footer{color:#8d887f;margin-top:50px}
@media(max-width:800px){
  .layout,.lead-grid,.stats{grid-template-columns:1fr}
  .shell{padding:64px 0}
}
"""


JS = """const spec = window.FOUNDRY_SPEC;
const form = document.getElementById("toolForm");
const result = document.getElementById("result");
const signal = document.getElementById("signal");
const resultCopy = document.getElementById("resultCopy");

const fmtCurrency = value => new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", maximumFractionDigits: 0 }).format(isFinite(value) ? value : 0);
const fmtNumber = value => new Intl.NumberFormat("en-US", { maximumFractionDigits: 1 }).format(isFinite(value) ? value : 0);

function addFields() {
  form.innerHTML = "";
  spec.fields.forEach(field => {
    const label = document.createElement("label");
    label.textContent = field.label;
    const input = document.createElement("input");
    input.type = "number";
    input.id = field.key;
    input.value = field.default ?? 0;
    input.dataset.type = field.type || "number";
    form.appendChild(label);
    form.appendChild(input);
  });
}

function values() {
  const data = {};
  spec.fields.forEach(field => {
    data[field.key] = Number(document.getElementById(field.key).value || 0);
  });
  return data;
}

function evaluate(data) {
  const formula = spec.formula || {};
  let value = 0;

  if (formula.type === "gap") {
    if (data.annualPremium !== undefined) value = data.annualPremium * (data.requiredDepositPct || 0) / 100 - (data.cashAvailable || 0);
    else if (data.projectValue !== undefined) value = data.projectValue * (data.materialCostPct || 0) / 100 - (data.cashAvailable || 0);
    else if (data.taxBalance !== undefined) value = data.taxBalance - (data.cashAvailable || 0);
    else if (data.weeklyPayroll !== undefined) value = data.weeklyPayroll - (data.cashAvailable || 0);
    else value = (data.amountNeeded || 0) - (data.cashAvailable || 0);
  } else if (formula.type === "opportunity_cost") {
    value = (data.heldPayout || 0) * (data.monthlyRoiPct || 0) / 100 * (data.daysHeld || 0) / 30;
  } else if (formula.type === "cost_of_delay") {
    value = (data.repairCost || 0) + (data.dailyRevenue || 0) * (data.downtimeDays || 0);
  } else if (formula.type === "commission_plan") {
    value = (data.targetIncome || 0) / Math.max(1, data.avgCommission || 1) / Math.max(0.01, (data.closeRatePct || 1) / 100);
  } else if (formula.type === "runway") {
    value = (data.raiseAmount || 0) / Math.max(1, data.monthlyBurn || 1) + (data.currentRunway || 0);
  } else if (formula.type === "score") {
    const revenue = data.monthlyRevenue || 0;
    const credit = data.creditScore || 600;
    const cash = data.cashAvailable || 0;
    value = Math.max(0, Math.min(100, Math.round((revenue / 1000) * 0.45 + ((credit - 500) / 3) + (cash / 1000) * 0.8)));
  }

  return Math.max(0, value);
}

function formatResult(value) {
  const formula = spec.formula || {};
  if (formula.resultFormat === "score") return `${Math.round(value)}/100`;
  if (formula.resultFormat === "currency") return fmtCurrency(value);
  return fmtNumber(value);
}

function band(value) {
  const formula = spec.formula || {};
  if (formula.resultFormat === "score") {
    if (value >= 75) return "High";
    if (value >= 50) return "Medium";
    return "Low";
  }
  if (value > 50000) return "High";
  if (value > 10000) return "Medium";
  return "Low";
}

function calc() {
  const data = values();
  const value = evaluate(data);
  const display = formatResult(value);
  result.textContent = display;
  signal.textContent = band(value);
  resultCopy.textContent = `${(spec.formula || {}).resultLabel || "Result"}: ${display}. ${(spec.outputs || [])[2] || "Route this lead to the next action."}`;
}

addFields();
calc();
document.getElementById("calculate").addEventListener("click", calc);
document.querySelectorAll("input").forEach(input => input.addEventListener("input", calc));
"""


def build(asset, spec, brand, target_dir):
    logic_profile = get_logic_profile(asset)
    copy_profile = generate_copy_profile(asset, logic_profile)
    design_system = get_design_system(asset)
    lead_flow = generate_lead_flow(asset, logic_profile, target_dir)

    context = common_context(asset, spec, brand, copy_profile, design_system)
    html_text = render(HTML, context)
    css_text = CSS
    js_text = JS
    readme_text = readme_for(spec, "calculator", asset, logic_profile, lead_flow)
    return write_bundle(target_dir, html_text=html_text, css_text=css_text, js_text=js_text, asset=asset, spec=spec, readme_text=readme_text)

