from __future__ import annotations

import html
import json
import shutil
from datetime import datetime
from pathlib import Path


def render(template: str, context: dict[str, object]) -> str:
    text = template
    for key, value in context.items():
        text = text.replace(f"[[{key}]]", str(value))
    return text


def esc(value: object) -> str:
    return html.escape(str(value or ""), quote=True)


def json_text(value: object) -> str:
    return json.dumps(value, indent=2, ensure_ascii=False)


def ensure_target_dir(target_dir: str | Path, force: bool = False) -> Path:
    target = Path(target_dir)
    if force and target.exists():
        shutil.rmtree(target)
    target.mkdir(parents=True, exist_ok=True)
    return target


def write_bundle(
    target_dir: str | Path,
    *,
    html_text: str,
    css_text: str,
    js_text: str,
    asset: dict,
    spec: dict,
    readme_text: str,
) -> Path:
    target = ensure_target_dir(target_dir)
    (target / "index.html").write_text(html_text, encoding="utf-8")
    (target / "styles.css").write_text(css_text, encoding="utf-8")
    (target / "app.js").write_text(js_text, encoding="utf-8")
    (target / "asset.json").write_text(json_text(asset), encoding="utf-8")
    (target / "asset-spec.json").write_text(json_text(spec), encoding="utf-8")
    (target / "README.md").write_text(readme_text, encoding="utf-8")
    return target


def common_context(asset: dict, spec: dict, brand: str | None = None) -> dict[str, object]:
    title = spec.get("title") or asset.get("name") or "Untitled Asset"
    brand_name = brand or spec.get("brand") or asset.get("brand") or "FoundryOS"
    outputs = spec.get("outputs") or []
    benefits = spec.get("benefits") or []
    modules = spec.get("modules") or []

    return {
        "ASSET_NAME": esc(title),
        "BRAND_NAME": esc(brand_name),
        "AUDIENCE": esc(spec.get("audience") or asset.get("audience") or ""),
        "PROBLEM": esc(spec.get("problem") or asset.get("problem") or ""),
        "PROMISE": esc(spec.get("promise") or ""),
        "CTA": esc(spec.get("primaryAction") or "Get My Result"),
        "ASSET_ID": esc(spec.get("id") or asset.get("id") or ""),
        "ASSET_TYPE": esc(spec.get("assetType") or asset.get("assetType") or ""),
        "TIER": esc(spec.get("tier") or asset.get("tier") or 1),
        "SPEC_JSON": json.dumps(spec, ensure_ascii=False),
        "FIELDS_JSON": json.dumps(spec.get("fields") or [], ensure_ascii=False),
        "FORMULA_JSON": json.dumps(spec.get("formula") or {}, ensure_ascii=False),
        "OUTPUTS": ", ".join(str(item) for item in outputs),
        "BENEFITS_HTML": "".join(f"<li>{esc(item)}</li>" for item in benefits),
        "MODULES_HTML": "".join(
            f"<div class='module'><b>{esc(module.get('name'))}</b><span>{esc(module.get('description'))}</span></div>"
            for module in modules
        ),
        "YEAR": str(datetime.now().year),
    }


def readme_for(spec: dict, builder_name: str) -> str:
    return (
        f"# {spec.get('title') or spec.get('id') or 'FoundryOS Asset'}\n\n"
        f"Generated by FoundryOS using the `{builder_name}` builder.\n\n"
        "Open `index.html`.\n\n"
        "Source files:\n"
        "- `index.html`\n"
        "- `styles.css`\n"
        "- `app.js`\n"
        "- `asset.json`\n"
        "- `asset-spec.json`\n"
    )
