from __future__ import annotations

from .common import common_context, readme_for, render, write_bundle


HTML = """<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8"/>
  <meta name="viewport" content="width=device-width,initial-scale=1"/>
  <title>[[ASSET_NAME]] | [[BRAND_NAME]]</title>
  <meta name="description" content="[[PROBLEM]]"/>
  <link rel="stylesheet" href="./styles.css"/>
</head>
<body>
  <main class="shell">
    <section class="hero">
      <p class="eyebrow">Dashboard · [[AUDIENCE]] · T[[TIER]]</p>
      <div class="hero-row">
        <div>
          <h1>[[ASSET_NAME]]</h1>
          <p class="lede">[[PROMISE]]</p>
        </div>
        <div class="hero-card">
          <span>Brand</span>
          <b>[[BRAND_NAME]]</b>
          <small>[[ASSET_TYPE]]</small>
        </div>
      </div>
    </section>
    <section class="dashboard">
      <aside class="sidebar panel">
        <h2>Overview</h2>
        <p class="copy">[[PROBLEM]]</p>
        <div class="mini-grid">
          <div><span>Modules</span><b id="moduleCount">0</b></div>
          <div><span>Fields</span><b id="fieldCount">0</b></div>
          <div><span>Status</span><b id="statusText">Live</b></div>
        </div>
        <button id="refresh">Refresh KPIs</button>
      </aside>
      <section class="content">
        <article class="panel">
          <h2>KPI cards</h2>
          <div class="kpis" id="kpis"></div>
        </article>
        <article class="panel">
          <h2>Trend board</h2>
          <div class="chart" id="chart"></div>
        </article>
      </section>
    </section>
    <section class="panel">
      <h2>Operating notes</h2>
      <ul class="bullets">[[BENEFITS_HTML]]</ul>
    </section>
    <footer class="footer">Generated by FoundryOS · [[BRAND_NAME]]</footer>
  </main>
  <script>window.FOUNDRY_SPEC=[[SPEC_JSON]];</script>
  <script src="./app.js"></script>
</body>
</html>
"""


CSS = """:root{
  color-scheme: dark;
  font-family: Inter, ui-sans-serif, system-ui;
  background:
    radial-gradient(circle at top left, rgba(120,255,212,.12), transparent 28%),
    radial-gradient(circle at top right, rgba(123,163,255,.18), transparent 26%),
    #081018;
  color:#f7fafc;
}
*{box-sizing:border-box}
body{margin:0;min-height:100vh;background:transparent}
.shell{width:min(1260px,94vw);margin:auto;padding:84px 0}
.hero{margin-bottom:28px}
.hero-row{display:flex;justify-content:space-between;gap:24px;align-items:flex-end}
.hero-card{min-width:220px;padding:18px 20px;border:1px solid #273852;border-radius:22px;background:rgba(11,18,29,.9)}
.hero-card span,.mini-grid span{display:block;color:#a9b8ca;font-size:13px}
.hero-card b{display:block;font-size:22px;margin:8px 0 4px}
.hero-card small{color:#7fd0ff}
.eyebrow{letter-spacing:.22em;text-transform:uppercase;color:#7fd0ff;font-size:12px}
h1{font-size:clamp(46px,7vw,84px);line-height:.92;margin:0 0 16px}
.lede{font-size:22px;color:#c8d4e2;max-width:720px;margin:0}
.dashboard{display:grid;grid-template-columns:320px 1fr;gap:24px;margin-bottom:24px}
.content{display:grid;gap:24px}
.panel{background:rgba(10,16,26,.94);border:1px solid #223147;border-radius:28px;padding:28px;box-shadow:0 20px 70px rgba(0,0,0,.22)}
.sidebar{position:sticky;top:18px;height:fit-content}
.mini-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:12px;margin:18px 0}
.mini-grid div{border:1px solid #2a3b53;border-radius:18px;padding:14px;background:rgba(9,14,22,.6)}
.mini-grid b{font-size:24px}
.kpis{display:grid;grid-template-columns:repeat(3,1fr);gap:14px}
.kpi{border:1px solid #2a3b53;border-radius:18px;padding:18px;background:rgba(11,18,29,.7)}
.kpi span{display:block;color:#a9b8ca;font-size:13px}
.kpi b{display:block;margin-top:8px;font-size:22px}
.chart{display:grid;gap:12px}
.bar{display:grid;grid-template-columns:160px 1fr 80px;gap:12px;align-items:center}
.track{height:12px;border-radius:999px;background:#111a27;border:1px solid #2a3b53;overflow:hidden}
.fill{height:100%;background:linear-gradient(90deg,#7fd0ff,#78ffda)}
.copy,.bullets{color:#c8d4e2;line-height:1.65}
.bullets{margin:0;padding-left:18px}
button,.button{display:inline-flex;align-items:center;justify-content:center;margin-top:18px;border:0;border-radius:999px;background:#f7fafc;color:#081018;padding:15px 22px;font-weight:900;cursor:pointer}
.footer{color:#91a2b9;margin-top:50px}
@media(max-width:960px){
  .hero-row,.dashboard,.kpis,.mini-grid{grid-template-columns:1fr}
  .hero-row{display:grid}
  .sidebar{position:static}
}
"""


JS = """const spec = window.FOUNDRY_SPEC;
const kpis = document.getElementById("kpis");
const chart = document.getElementById("chart");
const moduleCount = document.getElementById("moduleCount");
const fieldCount = document.getElementById("fieldCount");
const statusText = document.getElementById("statusText");

function formatCurrency(value) {
  return new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", maximumFractionDigits: 0 }).format(value);
}

function buildKpis() {
  const base = [
    { label: "Asset", value: spec.assetType || "dashboard" },
    { label: "Tier", value: `T${spec.tier || 1}` },
    { label: "Fields", value: `${(spec.fields || []).length}` }
  ];
  kpis.innerHTML = base.map(item => `<div class="kpi"><span>${item.label}</span><b>${item.value}</b></div>`).join("");
}

function buildChart() {
  const fields = spec.fields || [];
  const values = fields.slice(0, 6).map((field, index) => {
    const base = Number(field.default || 0);
    const offset = index * 7 + 12;
    return {
      label: field.label,
      value: Math.max(10, Math.min(100, Math.round((base % 100) + offset)))
    };
  });
  chart.innerHTML = values.map(item => `
    <div class="bar">
      <span>${item.label}</span>
      <div class="track"><div class="fill" style="width:${item.value}%"></div></div>
      <b>${item.value}</b>
    </div>
  `).join("");
}

function refresh() {
  moduleCount.textContent = String((spec.modules || []).length);
  fieldCount.textContent = String((spec.fields || []).length);
  statusText.textContent = (spec.modules || []).length > 0 ? "Operational" : "Live";
  buildKpis();
  buildChart();
}

document.getElementById("refresh").addEventListener("click", refresh);
refresh();
"""


def build(asset, spec, brand, target_dir):
    context = common_context(asset, spec, brand)
    return write_bundle(target_dir, html_text=render(HTML, context), css_text=CSS, js_text=JS, asset=asset, spec=spec, readme_text=readme_for(spec, "dashboard"))

