from __future__ import annotations

from .common import common_context, readme_for, render, write_bundle


HTML = """<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8"/>
  <meta name="viewport" content="width=device-width,initial-scale=1"/>
  <title>[[ASSET_NAME]] | [[BRAND_NAME]]</title>
  <meta name="description" content="[[PROBLEM]]"/>
  <link rel="stylesheet" href="./styles.css"/>
</head>
<body>
  <main class="shell">
    <section class="hero">
      <p class="eyebrow">Landing Page · [[AUDIENCE]]</p>
      <div class="hero-grid">
        <div>
          <h1>[[ASSET_NAME]]</h1>
          <p class="lede">[[PROMISE]]</p>
          <div class="cta-row">
            <a class="button" href="#lead">[[CTA]]</a>
            <span class="micro">[[ASSET_TYPE]] · T[[TIER]]</span>
          </div>
        </div>
        <aside class="hero-card">
          <span class="label">Core problem</span>
          <p>[[PROBLEM]]</p>
          <div class="pill-row">
            <span>Fast</span>
            <span>Clear</span>
            <span>Actionable</span>
          </div>
        </aside>
      </div>
    </section>
    <section class="proof">
      <article class="panel">
        <h2>The mechanism</h2>
        <ul class="bullets">[[BENEFITS_HTML]]</ul>
      </article>
      <article class="panel">
        <h2>What visitors get</h2>
        <div class="cards">
          <div><b>Instant clarity</b><span>A simple outcome or next step.</span></div>
          <div><b>Trust signal</b><span>Shows a concrete business mechanism.</span></div>
          <div><b>Higher intent</b><span>Moves the visitor toward a lead action.</span></div>
        </div>
      </article>
    </section>
    <section class="panel lead" id="lead">
      <div>
        <p class="eyebrow">Lead capture</p>
        <h2>Start here</h2>
        <p class="copy">[[PROMISE]]</p>
      </div>
      <div class="form-grid">
        <input placeholder="Name"/>
        <input placeholder="Email"/>
        <input placeholder="Phone"/>
      </div>
      <button id="submit">[[CTA]]</button>
      <p id="status" class="status">This is a static lead form shell for landing pages.</p>
    </section>
    <footer class="footer">Generated by FoundryOS · [[BRAND_NAME]]</footer>
  </main>
  <script>window.FOUNDRY_SPEC=[[SPEC_JSON]];</script>
  <script src="./app.js"></script>
</body>
</html>
"""


CSS = """:root{
  color-scheme: dark;
  font-family: Inter, ui-sans-serif, system-ui;
  background:
    radial-gradient(circle at 10% 10%, rgba(214,168,79,.26), transparent 25%),
    radial-gradient(circle at 90% 0%, rgba(118,146,255,.22), transparent 30%),
    linear-gradient(180deg,#06070d,#0b1018 40%,#05070b);
  color:#f7f3eb;
}
*{box-sizing:border-box}
body{margin:0;min-height:100vh;background:transparent}
.shell{width:min(1180px,94vw);margin:auto;padding:84px 0}
.hero{margin-bottom:28px}
.hero-grid{display:grid;grid-template-columns:1.15fr .85fr;gap:24px;align-items:center}
.eyebrow{letter-spacing:.24em;text-transform:uppercase;color:#d6a84f;font-size:12px}
h1{font-size:clamp(54px,8vw,100px);line-height:.9;margin:0 0 20px}
.lede{font-size:24px;color:#d9d2c7;max-width:760px;margin:0 0 24px}
.cta-row{display:flex;gap:14px;align-items:center;flex-wrap:wrap}
.button{display:inline-flex;align-items:center;justify-content:center;border:0;border-radius:999px;background:#f7f3eb;color:#06070d;padding:15px 24px;font-weight:900;text-decoration:none}
.micro{color:#b9b0a2}
.hero-card,.panel{background:rgba(13,17,25,.92);border:1px solid #273146;border-radius:28px;padding:28px;box-shadow:0 24px 80px rgba(0,0,0,.26)}
.hero-card .label{color:#d6a84f;text-transform:uppercase;letter-spacing:.2em;font-size:12px}
.hero-card p{color:#d9d2c7;line-height:1.7}
.pill-row{display:flex;gap:10px;flex-wrap:wrap}
.pill-row span,.cards div{border:1px solid #314055;border-radius:999px;padding:10px 14px;background:rgba(8,12,19,.55)}
.proof{display:grid;grid-template-columns:1fr 1fr;gap:24px;margin-bottom:24px}
.bullets{line-height:1.9;margin:0;padding-left:18px}
.cards{display:grid;gap:14px}
.cards div{border-radius:20px}
.cards b{display:block;margin-bottom:6px}
.cards span{color:#c7beb1}
.lead{display:grid;gap:18px}
.form-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:12px}
input,select,textarea{width:100%;border:1px solid #394154;background:#0b0d14;color:#fff;border-radius:14px;padding:15px;font-size:16px}
button{display:inline-flex;align-items:center;justify-content:center;border:0;border-radius:999px;background:#f7f3eb;color:#06070d;padding:15px 22px;font-weight:900;cursor:pointer;width:fit-content}
.status,.copy{color:#c7beb1;line-height:1.65}
.footer{color:#8d887f;margin-top:50px}
@media(max-width:900px){
  .hero-grid,.proof,.form-grid{grid-template-columns:1fr}
}
"""


JS = """const spec = window.FOUNDRY_SPEC;
const submit = document.getElementById("submit");
const status = document.getElementById("status");

function updateStatus(text) {
  status.textContent = text;
}

document.getElementById("lead")?.addEventListener("submit", event => event.preventDefault());
submit.addEventListener("click", () => {
  updateStatus(`Captured interest for ${spec.title || spec.id || "this asset"}. Wire this form to your CRM or email flow.`);
});

document.querySelectorAll('a[href^="#"]').forEach(link => {
  link.addEventListener("click", event => {
    const target = document.querySelector(link.getAttribute("href"));
    if (!target) return;
    event.preventDefault();
    target.scrollIntoView({ behavior: "smooth", block: "start" });
  });
});
"""


def build(asset, spec, brand, target_dir):
    context = common_context(asset, spec, brand)
    return write_bundle(target_dir, html_text=render(HTML, context), css_text=CSS, js_text=JS, asset=asset, spec=spec, readme_text=readme_for(spec, "landing_page"))

