from __future__ import annotations

from .common import common_context, readme_for, render, write_bundle


HTML = """<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8"/>
  <meta name="viewport" content="width=device-width,initial-scale=1"/>
  <title>[[ASSET_NAME]] | [[BRAND_NAME]]</title>
  <meta name="description" content="[[PROBLEM]]"/>
  <link rel="stylesheet" href="./styles.css"/>
</head>
<body>
  <main class="shell">
    <header class="topbar">
      <div>
        <p class="eyebrow">Portal · [[AUDIENCE]] · T[[TIER]]</p>
        <h1>[[ASSET_NAME]]</h1>
      </div>
      <a class="button" href="#intake">[[CTA]]</a>
    </header>
    <section class="overview">
      <article class="panel intro">
        <h2>Operating portal</h2>
        <p class="copy">[[PROMISE]]</p>
        <ul class="bullets">[[BENEFITS_HTML]]</ul>
      </article>
      <article class="panel modules">
        <h2>Modules</h2>
        <div class="modules">[[MODULES_HTML]]</div>
      </article>
    </section>
    <section class="workspace">
      <article class="panel" id="intake">
        <h2>Intake queue</h2>
        <div class="table" id="intakeTable"></div>
      </article>
      <article class="panel">
        <h2>Resource vault</h2>
        <div class="vault" id="vault"></div>
      </article>
    </section>
    <section class="panel">
      <h2>Input spec</h2>
      <div id="fieldList" class="field-list"></div>
      <p class="copy">This portal shell is static by default. Connect auth, storage, and routing when it goes live.</p>
    </section>
    <footer class="footer">Generated by FoundryOS · [[BRAND_NAME]]</footer>
  </main>
  <script>window.FOUNDRY_SPEC=[[SPEC_JSON]];</script>
  <script src="./app.js"></script>
</body>
</html>
"""


CSS = """:root{
  color-scheme: dark;
  font-family: Inter, ui-sans-serif, system-ui;
  background:
    radial-gradient(circle at top left, rgba(214,168,79,.2), transparent 25%),
    radial-gradient(circle at top right, rgba(127,208,255,.18), transparent 28%),
    #081018;
  color:#f8f5ee;
}
*{box-sizing:border-box}
body{margin:0;min-height:100vh;background:transparent}
.shell{width:min(1240px,94vw);margin:auto;padding:82px 0}
.topbar{display:flex;justify-content:space-between;align-items:flex-end;gap:24px;margin-bottom:28px}
.eyebrow{letter-spacing:.2em;text-transform:uppercase;color:#d6a84f;font-size:12px}
h1{font-size:clamp(48px,7vw,86px);line-height:.92;margin:0}
.button{display:inline-flex;align-items:center;justify-content:center;border:0;border-radius:999px;background:#f8f5ee;color:#081018;padding:15px 22px;font-weight:900;text-decoration:none}
.overview,.workspace{display:grid;grid-template-columns:1fr 1fr;gap:24px;margin-bottom:24px}
.panel{background:rgba(11,15,24,.94);border:1px solid #253347;border-radius:28px;padding:28px;box-shadow:0 20px 70px rgba(0,0,0,.24)}
.intro{display:flex;flex-direction:column;justify-content:space-between}
.copy{color:#c7beb1;line-height:1.7}
.bullets{line-height:1.9;margin:0;padding-left:18px}
.modules{display:grid;gap:12px}
.module{border:1px solid #30384b;border-radius:18px;padding:16px;background:rgba(8,12,19,.6)}
.module b{display:block;font-size:18px}
.module span{display:block;color:#c7beb1;margin-top:6px}
.table,.vault,.field-list{display:grid;gap:12px}
.row{display:grid;grid-template-columns:1.2fr .8fr .8fr;gap:10px;padding:14px 16px;border:1px solid #2b3243;border-radius:16px;background:rgba(8,12,19,.55)}
.row b,.row span{display:block}
.badge{display:inline-flex;align-items:center;justify-content:center;border-radius:999px;padding:4px 10px;background:rgba(127,208,255,.12);color:#7fd0ff;font-size:12px}
button,.button{cursor:pointer}
.footer{color:#8d887f;margin-top:50px}
@media(max-width:960px){
  .topbar,.overview,.workspace{grid-template-columns:1fr;display:grid}
  .topbar{align-items:start}
}
"""


JS = """const spec = window.FOUNDRY_SPEC;
const fieldList = document.getElementById("fieldList");
const intakeTable = document.getElementById("intakeTable");
const vault = document.getElementById("vault");

function renderFields() {
  fieldList.innerHTML = (spec.fields || []).map(field => `
    <div class="module">
      <b>${field.label}</b>
      <span>${field.key} · ${field.type || "number"} · default ${field.default ?? 0}</span>
    </div>
  `).join("");
}

function renderIntake() {
  const items = [
    { name: "New lead", status: "New", owner: "Sales" },
    { name: "Qualified contact", status: "Reviewing", owner: "Ops" },
    { name: "Active client", status: "Closed", owner: "Service" }
  ];
  intakeTable.innerHTML = items.map(item => `
    <div class="row">
      <div>
        <b>${item.name}</b>
        <span>${item.owner}</span>
      </div>
      <div><span class="badge">${item.status}</span></div>
      <div><span>${(spec.tier || 1) >= 3 ? "Portal" : "Workspace"}</span></div>
    </div>
  `).join("");
}

function renderVault() {
  const items = [
    "Playbook",
    "Template pack",
    "FAQ",
    "Approval checklist"
  ];
  vault.innerHTML = items.map(item => `
    <div class="row">
      <div>
        <b>${item}</b>
        <span>Shared operational resource</span>
      </div>
      <div><span class="badge">Ready</span></div>
      <div><span>Open</span></div>
    </div>
  `).join("");
}

renderFields();
renderIntake();
renderVault();
"""


def build(asset, spec, brand, target_dir):
    context = common_context(asset, spec, brand)
    return write_bundle(target_dir, html_text=render(HTML, context), css_text=CSS, js_text=JS, asset=asset, spec=spec, readme_text=readme_for(spec, "portal"))

