from __future__ import annotations

from .common import common_context, readme_for, render, write_bundle


HTML = """<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8"/>
  <meta name="viewport" content="width=device-width,initial-scale=1"/>
  <title>[[ASSET_NAME]] | [[BRAND_NAME]]</title>
  <meta name="description" content="[[PROBLEM]]"/>
  <link rel="stylesheet" href="./styles.css"/>
</head>
<body>
  <main class="shell">
    <section class="hero">
      <p class="eyebrow">Scorecard · [[AUDIENCE]] · T[[TIER]]</p>
      <h1>[[ASSET_NAME]]</h1>
      <p class="lede">[[PROMISE]]</p>
    </section>
    <section class="deck">
      <article class="score-panel">
        <p class="eyebrow">Readiness Score</p>
        <div class="ring">
          <div class="ring-inner"><span id="score">0</span><small>/100</small></div>
        </div>
        <p id="signal" class="signal">Waiting for inputs</p>
      </article>
      <article class="panel">
        <h2>Assessment inputs</h2>
        <p class="copy">[[PROBLEM]]</p>
        <form id="toolForm" class="fields"></form>
        <button id="calculate">[[CTA]]</button>
      </article>
    </section>
    <section class="grid">
      <article class="panel">
        <h2>Score bands</h2>
        <div class="bands">
          <div><b>High</b><span>Ready for a direct offer or handoff.</span></div>
          <div><b>Medium</b><span>Qualified, but needs more context or proof.</span></div>
          <div><b>Low</b><span>Capture the lead and nurture before action.</span></div>
        </div>
      </article>
      <article class="panel">
        <h2>Why it matters</h2>
        <ul class="bullets">[[BENEFITS_HTML]]</ul>
      </article>
    </section>
    <section class="panel footer-panel">
      <h2>Next step</h2>
      <p id="resultCopy" class="copy">This scorecard will summarize the fit and recommend the next action.</p>
      <button>[[CTA]]</button>
    </section>
    <footer class="footer">Generated by FoundryOS · [[BRAND_NAME]]</footer>
  </main>
  <script>window.FOUNDRY_SPEC=[[SPEC_JSON]];</script>
  <script src="./app.js"></script>
</body>
</html>
"""


CSS = """:root{
  color-scheme: dark;
  font-family: Inter, ui-sans-serif, system-ui;
  background:
    radial-gradient(circle at top, rgba(103,162,255,.23), transparent 28%),
    radial-gradient(circle at 100% 10%, rgba(78,214,163,.12), transparent 30%),
    #071019;
  color:#f6f8fb;
}
*{box-sizing:border-box}
body{margin:0;min-height:100vh;background:transparent}
.shell{width:min(1140px,92vw);margin:auto;padding:88px 0}
.hero{margin-bottom:40px}
.eyebrow{letter-spacing:.2em;text-transform:uppercase;color:#7fd0ff;font-size:12px}
h1{font-size:clamp(48px,8vw,88px);line-height:.92;margin:0 0 18px}
.lede{font-size:22px;color:#c8d4e2;max-width:760px;margin:0}
.deck{display:grid;grid-template-columns:.9fr 1.1fr;gap:24px;margin-bottom:24px}
.grid{display:grid;grid-template-columns:1fr 1fr;gap:24px;margin-bottom:24px}
.panel,.score-panel{background:rgba(9,16,28,.92);border:1px solid #24344d;border-radius:28px;padding:28px;box-shadow:0 24px 80px rgba(0,0,0,.28)}
.score-panel{display:flex;flex-direction:column;align-items:center;justify-content:center;text-align:center;gap:18px;min-height:420px}
.ring{width:240px;height:240px;border-radius:50%;background:conic-gradient(#7fd0ff 0 0,#20334d 0 100%);padding:18px}
.ring-inner{width:100%;height:100%;border-radius:50%;display:flex;flex-direction:column;align-items:center;justify-content:center;background:radial-gradient(circle at top,#142235,#0a1019 72%);border:1px solid #2a3d57}
.ring-inner span{font-size:76px;font-weight:950;line-height:1}
.ring-inner small{color:#c8d4e2;font-size:20px}
.signal{margin:0;color:#91ffbf;font-weight:800}
.fields{display:grid;gap:14px;margin-top:14px}
label{display:block;margin:0 0 6px;color:#e2e9f2}
input,select,textarea{width:100%;border:1px solid #31465f;background:#08111a;color:#fff;border-radius:14px;padding:15px;font-size:16px}
button,.button{display:inline-flex;align-items:center;justify-content:center;margin-top:18px;border:0;border-radius:999px;background:#f6f8fb;color:#071019;padding:15px 22px;font-weight:900;text-decoration:none;cursor:pointer}
.copy{color:#c8d4e2;line-height:1.6}
.bands{display:grid;gap:14px}
.bands div{border:1px solid #2a3d57;border-radius:18px;padding:18px;background:rgba(11,20,32,.6)}
.bands b{display:block;margin-bottom:6px}
.bands span{color:#c8d4e2}
.bullets{line-height:1.9;margin:0;padding-left:18px}
.footer-panel{text-align:center}
.footer{color:#91a2b9;margin-top:50px}
@media(max-width:900px){
  .deck,.grid{grid-template-columns:1fr}
}
"""


JS = """const spec = window.FOUNDRY_SPEC;
const form = document.getElementById("toolForm");
const score = document.getElementById("score");
const signal = document.getElementById("signal");
const resultCopy = document.getElementById("resultCopy");

function addFields() {
  form.innerHTML = "";
  spec.fields.forEach(field => {
    const label = document.createElement("label");
    label.textContent = field.label;
    const input = document.createElement("input");
    input.type = "number";
    input.id = field.key;
    input.value = field.default ?? 0;
    form.appendChild(label);
    form.appendChild(input);
  });
}

function values() {
  const data = {};
  spec.fields.forEach(field => {
    data[field.key] = Number(document.getElementById(field.key).value || 0);
  });
  return data;
}

function scoreValue(data) {
  const formula = spec.formula || {};
  if (formula.type === "score") {
    const revenue = data.monthlyRevenue || 0;
    const credit = data.creditScore || 600;
    const cash = data.cashAvailable || 0;
    return Math.max(0, Math.min(100, Math.round((revenue / 1000) * 0.45 + ((credit - 500) / 3) + (cash / 1000) * 0.8)));
  }

  const values = Object.values(data);
  const total = values.reduce((acc, value) => acc + Math.abs(Number(value) || 0), 0);
  const scaled = Math.max(0, Math.min(100, Math.round(total / Math.max(1, values.length * 1000))));
  return scaled;
}

function band(value) {
  if (value >= 75) return "High fit";
  if (value >= 50) return "Qualified with gaps";
  return "Needs nurture";
}

function calc() {
  const data = values();
  const value = scoreValue(data);
  score.textContent = value;
  signal.textContent = band(value);
  resultCopy.textContent = `${(spec.formula || {}).resultLabel || "Readiness score"} is ${value}/100. ${(spec.outputs || [])[0] || "Use the score to route the lead."}`;
  const ring = document.querySelector(".ring");
  ring.style.background = `conic-gradient(#7fd0ff 0 ${value}%, #20334d ${value}% 100%)`;
}

addFields();
calc();
document.getElementById("calculate").addEventListener("click", calc);
document.querySelectorAll("input").forEach(input => input.addEventListener("input", calc));
"""


def build(asset, spec, brand, target_dir):
    context = common_context(asset, spec, brand)
    html_text = render(HTML, context)
    return write_bundle(target_dir, html_text=html_text, css_text=CSS, js_text=JS, asset=asset, spec=spec, readme_text=readme_for(spec, "scorecard"))

