from __future__ import annotations

from .common import common_context, readme_for, render, write_bundle


HTML = """<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8"/>
  <meta name="viewport" content="width=device-width,initial-scale=1"/>
  <title>[[ASSET_NAME]] | [[BRAND_NAME]]</title>
  <meta name="description" content="[[PROBLEM]]"/>
  <link rel="stylesheet" href="./styles.css"/>
</head>
<body>
  <main class="shell">
    <section class="hero">
      <p class="eyebrow">Simulator · [[AUDIENCE]] · T[[TIER]]</p>
      <h1>[[ASSET_NAME]]</h1>
      <p class="lede">[[PROMISE]]</p>
    </section>
    <section class="grid">
      <article class="panel">
        <h2>Scenario controls</h2>
        <p class="copy">[[PROBLEM]]</p>
        <form id="toolForm" class="fields"></form>
        <button id="calculate">[[CTA]]</button>
      </article>
      <article class="panel hero-panel">
        <p class="eyebrow">Simulation output</p>
        <div class="result" id="result">—</div>
        <p id="resultCopy" class="copy">Adjust the scenario inputs to model the outcome.</p>
        <div class="meter"><span id="meter"></span></div>
        <div class="stats">
          <div><span>Mode</span><b>[[ASSET_TYPE]]</b></div>
          <div><span>Tier</span><b>T[[TIER]]</b></div>
          <div><span>Signal</span><b id="signal">—</b></div>
        </div>
      </article>
    </section>
    <section class="panel">
      <h2>Simulation notes</h2>
      <ul class="bullets">[[BENEFITS_HTML]]</ul>
    </section>
    <footer class="footer">Generated by FoundryOS · [[BRAND_NAME]]</footer>
  </main>
  <script>window.FOUNDRY_SPEC=[[SPEC_JSON]];</script>
  <script src="./app.js"></script>
</body>
</html>
"""


CSS = """:root{
  color-scheme: dark;
  font-family: Inter, ui-sans-serif, system-ui;
  background:
    radial-gradient(circle at 15% 15%, rgba(255,174,95,.2), transparent 25%),
    radial-gradient(circle at 85% 5%, rgba(92,154,255,.22), transparent 26%),
    linear-gradient(180deg,#090b12,#0a1019 40%,#04060a);
  color:#f7f6f2;
}
*{box-sizing:border-box}
body{margin:0;min-height:100vh;background:transparent}
.shell{width:min(1140px,92vw);margin:auto;padding:88px 0}
.hero{margin-bottom:40px}
.eyebrow{letter-spacing:.22em;text-transform:uppercase;color:#f1b15d;font-size:12px}
h1{font-size:clamp(48px,8vw,92px);line-height:.92;margin:0 0 18px}
.lede{font-size:22px;color:#d7d1c4;max-width:760px;margin:0}
.grid{display:grid;grid-template-columns:1fr 1fr;gap:24px;margin-bottom:24px}
.panel{background:rgba(13,16,25,.94);border:1px solid #2b3444;border-radius:28px;padding:28px;box-shadow:0 20px 70px rgba(0,0,0,.22)}
.hero-panel{display:flex;flex-direction:column;justify-content:center;gap:14px}
.fields{display:grid;gap:14px;margin-top:14px}
label{display:block;margin:0 0 6px;color:#e8e1d2}
input,select,textarea{width:100%;border:1px solid #394154;background:#0b0d14;color:#fff;border-radius:14px;padding:15px;font-size:16px}
button,.button{display:inline-flex;align-items:center;justify-content:center;margin-top:18px;border:0;border-radius:999px;background:#f7f6f2;color:#0b0d14;padding:15px 22px;font-weight:900;text-decoration:none;cursor:pointer}
.result{font-size:48px;font-weight:950;color:#91ffbf}
.copy{color:#c7beb1;line-height:1.6}
.stats{display:grid;grid-template-columns:repeat(3,1fr);gap:14px;margin-top:10px}
.stats div{border:1px solid #30384b;border-radius:18px;padding:18px;background:rgba(9,13,20,.6)}
.stats span{display:block;color:#c7beb1;font-size:13px}
.stats b{font-size:22px}
.meter{height:16px;border-radius:999px;background:#111826;border:1px solid #314055;overflow:hidden}
.meter span{display:block;height:100%;width:0;background:linear-gradient(90deg,#ffb057,#91ffbf);transition:width .25s ease}
.bullets{line-height:1.9;margin:0;padding-left:18px}
.footer{color:#8d887f;margin-top:50px}
@media(max-width:900px){
  .grid,.stats{grid-template-columns:1fr}
}
"""


JS = """const spec = window.FOUNDRY_SPEC;
const form = document.getElementById("toolForm");
const meter = document.getElementById("meter");
const result = document.getElementById("result");
const signal = document.getElementById("signal");
const resultCopy = document.getElementById("resultCopy");

function addFields() {
  form.innerHTML = "";
  spec.fields.forEach(field => {
    const label = document.createElement("label");
    label.textContent = field.label;
    const input = document.createElement("input");
    input.type = "number";
    input.id = field.key;
    input.value = field.default ?? 0;
    form.appendChild(label);
    form.appendChild(input);
  });
}

function values() {
  const data = {};
  spec.fields.forEach(field => {
    data[field.key] = Number(document.getElementById(field.key).value || 0);
  });
  return data;
}

function evaluate(data) {
  const formula = spec.formula || {};
  if (formula.type === "score") {
    const revenue = data.monthlyRevenue || 0;
    const credit = data.creditScore || 600;
    const cash = data.cashAvailable || 0;
    return Math.max(0, Math.min(100, Math.round((revenue / 1000) * 0.45 + ((credit - 500) / 3) + (cash / 1000) * 0.8)));
  }
  if (formula.type === "gap") {
    if (data.annualPremium !== undefined) return Math.max(0, data.annualPremium * (data.requiredDepositPct || 0) / 100 - (data.cashAvailable || 0));
    if (data.projectValue !== undefined) return Math.max(0, data.projectValue * (data.materialCostPct || 0) / 100 - (data.cashAvailable || 0));
    if (data.taxBalance !== undefined) return Math.max(0, data.taxBalance - (data.cashAvailable || 0));
    if (data.weeklyPayroll !== undefined) return Math.max(0, data.weeklyPayroll - (data.cashAvailable || 0));
    return Math.max(0, (data.amountNeeded || 0) - (data.cashAvailable || 0));
  }
  if (formula.type === "opportunity_cost") return Math.max(0, (data.heldPayout || 0) * (data.monthlyRoiPct || 0) / 100 * (data.daysHeld || 0) / 30);
  if (formula.type === "cost_of_delay") return Math.max(0, (data.repairCost || 0) + (data.dailyRevenue || 0) * (data.downtimeDays || 0));
  if (formula.type === "commission_plan") return Math.max(0, (data.targetIncome || 0) / Math.max(1, data.avgCommission || 1) / Math.max(0.01, (data.closeRatePct || 1) / 100));
  if (formula.type === "runway") return Math.max(0, (data.raiseAmount || 0) / Math.max(1, data.monthlyBurn || 1) + (data.currentRunway || 0));
  return 0;
}

function formatValue(value) {
  const formula = spec.formula || {};
  if (formula.resultFormat === "score") return `${Math.round(value)}/100`;
  if (formula.resultFormat === "currency") return new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", maximumFractionDigits: 0 }).format(value);
  return new Intl.NumberFormat("en-US", { maximumFractionDigits: 1 }).format(value);
}

function band(value) {
  const formula = spec.formula || {};
  if (formula.resultFormat === "score") {
    if (value >= 75) return "High";
    if (value >= 50) return "Medium";
    return "Low";
  }
  if (value > 50000) return "High";
  if (value > 10000) return "Medium";
  return "Low";
}

function calc() {
  const data = values();
  const value = evaluate(data);
  const display = formatValue(value);
  result.textContent = display;
  signal.textContent = band(value);
  meter.style.width = `${Math.min(100, Math.max(4, value))}%`;
  resultCopy.textContent = `${(spec.formula || {}).resultLabel || "Simulation output"}: ${display}. ${(spec.outputs || [])[2] || "Use this scenario to guide the next move."}`;
}

addFields();
calc();
document.getElementById("calculate").addEventListener("click", calc);
document.querySelectorAll("input").forEach(input => input.addEventListener("input", calc));
"""


def build(asset, spec, brand, target_dir):
    context = common_context(asset, spec, brand)
    return write_bundle(target_dir, html_text=render(HTML, context), css_text=CSS, js_text=JS, asset=asset, spec=spec, readme_text=readme_for(spec, "simulator"))

